#Uncomment the volumes mount for live coding
version: '2'
services:
  # nginx:
  #   image: nginx
  #   volumes:
  #     - ./vhosts/default.conf:/etc/nginx/conf.d/default.conf
  #     #- ./certs/:/etc/nginx/ssl/
  #   depends_on:
  #     - live
  #   ports:
  #     - "443:443"
  live:
    image: dynedjakartacontainers/liveb2i:1.0.0
    ports:
      #- "8181:80"
      - "80:80"
    volumes:
      - ./live/.:/var/www/html/
    env_file: .env
